// <auto-generated />
namespace FortyFiftySixDeegrees.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddReadypropertytoOrders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddReadypropertytoOrders));
        
        string IMigrationMetadata.Id
        {
            get { return "202112191803180_Add Ready property to Orders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
